### ISSUE TITLE
Autogenerate validator_key.json

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DAppNodePackage-NEAR#9]
Check https://near-nodes.io/validator/validator-bootcamp#check-the-validator_keyjson

**Comment by alexpeterson91** [comment]
new wallet implementations will make this next to impossible due to dozens of wallets being supported in next wallet UI update, current wallet UI is not fully supported anymore and was sunset ~7 months ago.  New wallets allow for use with several 3rd party wallets and hardware wallets like ledger, where autogenerating a validator key will not be possible.

**Comment by alexpeterson91** [comment]
there are very very few active NEAR users on the platform right now, and none stake/validate with it.  Will return to this when new wallet(s) are added and if theres even a demand by users for NEAR staking services on dappnode, other services make it much easier even ledger has it built into Ledger Live's staking/earn dashboard now.  
For now am closing this and just maintaining this package as an RPC node, and will add new wallets when time allows, but theres too little interest to even make it a low priority .  
Will be changed if there is any user demand change but its currently at 0 and has been for far too long.  only a couple users use this package and they only use it as RPC nodes
